### ISSUE TITLE
Attributes with Value 0

### ISSUE THREAD

**Issue by n0um3n4** [fouita/svelte-tw-data-table#2]
## Expected Behavior
When object's attributes have integer value of 0, user should be able to see the value 0.

## Current Behavior
There are columns with value 0 in the white space.

![Screen Shot 2021-02-20 at 10 39 11](https://user-images.githubusercontent.com/944683/108602511-e4a86900-7367-11eb-8b14-e3113b49853c.png)

**Comment by haynajjar** [comment]
Fixed on the new version 0.0.2, Thanks
